server:
  port: 8080
# Spring boot by default configurs the H2 Datasource So I do not need to configure Datasource explicitly.
# But showing how we have to configure the Datasource ( postgres/oracle/other) 

#Creating Datasource , Enabling H2 Console and Path
spring:  datasource:    url: jdbc:h2:mem:customerdata
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:    database-platform: org.hibernate.dialect.H2Dialect
  h2:    console:      enabled: true
      path: /h2
  application:    name: Customer Data